CREATE TABLE users (
    id INT (11) NOT NULL AUTO_INCREMENT,
    username VARCHAR (30) NOT NULL,
    pwd VARCHAR (255) NOT NULL,
    email VARCHAR (100) NOT NULL,
    created_at DATETIME  NOT NULL DEFAULT CURRENT_TIME,
    PRIMARY KEY (id)
    );


    ALTER TABLE users
    ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'student';

    ALTER TABLE users ADD COLUMN age INT;
    ALTER TABLE users ADD COLUMN gender VARCHAR(10);
    ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
